version: '2'
services:
  database:
    container_name: docker_pg
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=listerlyify_dev
  service:
    container_name: listerlyify_service
    build: .
    image: listerlyify_service
    command: /opt/listerlyify/run-service
    ports:
      - "4000:4000"
      - "5858:5858"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - .:/opt/listerlyify
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
  deps-install:
    container_name: listerlyify_install
    build: .
    command: /opt/listerlyify/run-install
    volumes:
      - .:/opt/listerlyify
